# general settings
name: HAT_256_finetune_psnr
model_type: HATModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: custom
    type: PairedImageDataset
    dataroot_gt: datasets/DaconVariation/train/hr
    dataroot_lq: datasets/DaconVariation/train/lr
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 10
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: weights/HAT_OuDD_bicubic_19epoch.pth
  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [39360, 62976, 70848, 75572]
    gamma: 0.5

  total_iter: 78720
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1.0
    reduction: mean

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1.312e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
